### ISSUE TITLE
[FEATURE]: Email Templates > SuperAdmin Email Management Dashboard > Template Preview Component #43

### ISSUE THREAD

**Issue by elitenoire** [hngprojects/hng_boilerplate_remix#104]
## Description
Create the Preview Component for HTML Templates used in the Super Admin Email Management Dashboard for creating and editing email templates.

## Acceptance Criteria
- Reusable Preview Component for HTML Templates
- Component adapts to scrollable Templates
- Components shrink templates to fit
- Component has a fluid width
- Component adheres to the brand colors and design

## Expected Outcome

- User should be able to view any HTML Template
- User should be able to scroll the Template if longer than the Preview Component
- User should be able to edit the HTML markup
- Responsive design of Component

## Purpose
As a User, I want to be able to preview or edit Html Email Templates

## Requirement

-  custom scrollbar design

## Task
- [ ] Implement Reusable Preview Component
- [ ] Component has a scrollable content
- [ ] Scrollbar is visible when content overflows its container
- [ ] Make Preview Component responsive with a fluid width
- [ ] Preview Component should render html template as prop
- [ ] Preview Component should have a prop 'mode' - preview and edit
- [ ] Preview mode (the default) displays the HTML template
- [ ] Edit mode displays the HTML Markup as content editable 
- [ ] Supports `onEdit` / `onChange` callback to pass edited markup
- [ ] HTML Template scales to fit its container
- [ ] Component adheres to the brand design and color scheme

## Deadline
You are given till Saturday 20th July 22:00PM WAT to complete the task.

## Picture
![preview_email_template](https://github.com/user-attachments/assets/9d1a0352-d713-4198-90a9-4f2f0d5d22a2)

![preview_email_template_scaled](https://github.com/user-attachments/assets/83fceff7-2d4d-4965-9897-26a45e9c5b91)

## Dev Mode Figma Link
https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=2266-27056&m=dev
https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=2319-10446&m=dev
