### ISSUE TITLE
[FEATURE] Create More Action Component on Table Listing

### ISSUE THREAD

**Issue by taiwonaf** [hngprojects/hng_boilerplate_remix#110]
## Description
Develop the More Action Component Popover button. This component will be used on table components to view more actions like edit, delete etc. This component should function properly and be fully responsive on all screen sizes.

## Acceptance Criteria

- Implement the More Action Component button that functions appropriately using [popover guideline](https://ui.shadcn.com/docs/components/popover)
- Ensure the component is visually appealing and follow the design accordingly
- Use the same icon used on the design with alteration
- Maintain accessibility standards and arial labels

### Requirements

- The component should accept a list of more actions to perform example, Edit, Delete, View etc
- Each actions should return corresponding events when there are clicked
- The component should be clickable and drops down further clickable actions
- The component should follow the design

### Test

- Manual testing

### Task

- [ ] Develop the component based on the specific requirements
- [ ] Implement support for the various props that will be sent to the component
- [ ] Implement support for functions that will be performed when action values are clicked
- [ ] Write unit test to validate component behavior
- [ ] Verify accessibility features are properly implemented.

### Link
[Fimga](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=2179-38028&m=dev)

### Image
<img width="211" alt="Screenshot 2024-07-18 at 08 52 46" src="https://github.com/user-attachments/assets/31cd3edb-896f-4bcb-957d-5fad1e019173">
