### ISSUE TITLE
[FEAT] Organization settings  > Roles and permission page > Implement  Create role modal

### ISSUE THREAD

**Issue by oreoluwa212** [hngprojects/hng_boilerplate_remix#13]
## **Description**  
Create the "Create Role" Modal for defining customized responsibilities for collaborative success.

## **Acceptance Criteria**
- Modal has a title "Create Role"
- Modal has a name input field with placeholder "e.g: IT Staff"
- Modal has a description input field with placeholder "describe role"
- Modal has a "Cancel" button
- Modal has a "Create Role" button
- Modal adheres to the brand colors and design
- Modal is responsive across device widths

## **Expected Outcome**
- User should be able to input the name and description for a new role
- User should be able to cancel the role creation process
- User should be able to create a role by clicking the "Create Role" button
- Modal should be responsive on different devices

## **Purpose**
As a user, I want to define customized responsibilities by creating new roles.

## **Requirement**
- Implement the modal with the title, input fields, and buttons as described
- Ensure the modal follows the brand's design guidelines
- Make sure the modal is responsive

## **Task**
- [ ] Create a modal component
- [ ] Add a title "Create Role"
- [ ] Add an input field for the name with the placeholder "e.g: IT Staff"
- [ ] Add an input field for the description with the placeholder "describe role"
- [ ] Add a "Cancel" button
- [ ] Add a "Create Role" button
- [ ] Ensure the modal follows brand colors and design
- [ ] Ensure the modal is responsive

## **Picture**  
![Create role modal](https://github.com/user-attachments/assets/a0636442-ff84-4177-a8ce-806290c787dd)

## Dev Mode
[Dev Mode Link](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=118-44881&m=dev)

**Comment by hokageCodes** [comment]
I would like to attempt this

**Comment by JO-YE** [comment]
issue has been self-assigned.  as it wasn't assigned to anyone since the issue was approved

**Comment by hokageCodes** [comment]
Okay please can it be assigned to me
