### ISSUE TITLE
[FEATURE] Create Payment Card Component With different states

### ISSUE THREAD

**Issue by crystal4000** [hngprojects/hng_boilerplate_remix#156]
## Description
Develop a card payment component. This component includes a toggle radio button to select Billing Options. This component will be used in the upgrade plan page to select method of payment.

## Acceptance Criteria

- The card must be implemented according to design
- The card component must be fully responsive and visually appealing
- Meet accessibility standards, apply alt text where necessary

### Requirements
**The card should have the following props and element**

- Card header
- Optional amount value
- Optional billing period
- Optional Image or logo
- A toggle radio box

### Task
- [ ] Ensure UI consistency
- [ ] Ensure Component can receive prop values
- [ ] Develop component according to the design
- [ ] Implement toggle radio button
- [ ] Implement logo or image section

### Link
[Figma link](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=10-16589&m=dev)

### Image
<img width="338" alt="Screenshot 2024-07-17 at 17 35 02" src="https://github.com/user-attachments/assets/984a7391-400c-4d0b-a234-d1dfc2c8d77b">

**Comment by crystal4000** [comment]
Duplicate
