### ISSUE TITLE
[FEATURE]: Email Templates > SuperAdmin Email Management Dashboard > New Template with HTML

### ISSUE THREAD

**Issue by elitenoire** [hngprojects/hng_boilerplate_remix#2]
## Description
Create the Page for Generating New Email Template with HTML found in the Super Admin Email Management Dashboard

## Acceptance Criteria
-  Reusable Breadcrumbs
- Page title and description
-  Well validated form with input and button submission
- Tips Component with a defined title and bulleted tips
- Components adheres to the brand colors and design
- Responsive design of page

## Expected Outcome

- User should be able to see a tips card for helpful information
- User should be able to input or paste link to a html file in the input field
- User should be able to click the button to generate the new html template
- On success, user should be directed to the preview generated html page

## Purpose
As a User, I want to input a link pointing to my Html file to generate a new email template

## Requirement

-  Installs and uses shadcn-ui alert
-  Makes use of the form, Input and button components
-  Makes use of the Breadcrumbs component

## Task
- [x] Has Breadcrumbs for easy navigation
- [x] Implement Page with a clear title and description
- [x] Implement Tips component using shadcn-ui alert
- [x] Implement Form input with label and button
- [x] validate that link from form input points to .html file
- [x] button generates template on form submission
- [x] navigate to preview template page on successful template generation
- [x] Components adhere to the brand design and color scheme
- [x] Page is responsive across device widths

## Deadline
You are given till Saturday 20th July 12:00PM WAT to complete the task.

## Picture
![generate_email_template](https://github.com/user-attachments/assets/afa266b8-3599-4225-a4ca-4c028e1f361c)

## Dev Mode Figma Link
https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=63-69677&m=dev

**Comment by lilbobb** [comment]
ownership claimed, please stay away.

**Comment by lilbobb** [comment]
the picture "generate-email-template" is not opening from my end, have tried everything possible.

**Comment by elitenoire** [comment]
> the picture "generate-email-template" is not opening from my end, have tried everything possible.

Image link has been updated, if it is still not opening check the figma file for a visual representation.

**Comment by lilbobb** [comment]
Thanks, I can see it now.
