### ISSUE TITLE
[FEATURE] Create and implement the API integration of the comment section of the dynamic blog pages

### ISSUE THREAD

**Issue by taiwonaf** [hngprojects/hng_boilerplate_remix#23]
# **Description**
Implement both the web and mobile view of the blog details page comment section excluding and integrate the api to map out all comments on the blog also api to make new comments.

# **Acceptance Criteria**
- Pixel perfect implementaiton
- Responsive implementation
- Clean code
- Make use of reusable components where needed, make one if needed
- Follow the [contribution guidelines](https://github.com/hngprojects/hng_boilerplate_nextjs/blob/0acf613964ea064ae211a91d0a74d13938e4bc23/CONTRIBUTING.md) and [code of conduct](https://github.com/hngprojects/hng_boilerplate_nextjs/blob/0acf613964ea064ae211a91d0a74d13938e4bc23/CODE_OF_CONDUCT.md)

# **Requirements**
- Show all current comments on the blog
- Text area to input comment with required validation
- Able to make new blog using the required api endpoint
- Realtime update of the rendered comment

# **Testing**
- Manually test

# **Tasks**
- [ ] Implement all the sections in the design
- [ ] Responsiveness across all screens
- [ ] Make use of reusable components where needed- [ ] Proper commit message

# **Images**
![Frame 53129](https://github.com/user-attachments/assets/b0548e35-ae17-4e45-b587-e1320260ef1a)
![Frame 53129](https://github.com/user-attachments/assets/a73470d7-e71d-4082-9468-982624cb83fe)

[Figma design](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=1632-11418&m=dev)

**Comment by maetheartist** [comment]
I will like to work on this issue.
