### ISSUE TITLE
[FEAT] Api integration for the latest articles page

### ISSUE THREAD

**Issue by taiwonaf** [hngprojects/hng_boilerplate_remix#25]
# **Description**
Integrate the api to map out the latest articles in the latest articles page. **(Note: use dummy data to simulate api implementation )**

# **Acceptance Criteria**
- Pixel perfect implementaiton
- Responsive implementation
- Clean code
- Make use of reusable components where needed, make one if needed
- Follow the [contribution guidelines](https://github.com/hngprojects/hng_boilerplate_nextjs/blob/0acf613964ea064ae211a91d0a74d13938e4bc23/CONTRIBUTING.md) and [code of conduct](https://github.com/hngprojects/hng_boilerplate_nextjs/blob/0acf613964ea064ae211a91d0a74d13938e4bc23/CODE_OF_CONDUCT.md)

# **Requirements**
- Map out the list of latest articles with pagination
- Proper error handling
- Proper loading indicator
- None breaking api integration

# **Testing**
- Manually test before making a pr

# **Tasks**
- [ ] Implement all the sections in the design
- [ ] Responsiveness across all screens
- [ ] Make use of reusable components where needed
- [ ] Proper commit message

# **Images**
![Blogs](https://github.com/user-attachments/assets/fab0427f-4253-4afd-b596-fa15bbe32e61)

[Figma design](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=1632-11225&m=dev)
