### ISSUE TITLE
[FEAT] External static Page > Sub Page Hero Component

### ISSUE THREAD

**Issue by taiwonaf** [hngprojects/hng_boilerplate_remix#31]
# **Description**
Implement both the mobile and web view of the static pages sub pages hero section. This section should be reusable accepts props of page title and page description.

# **Acceptance Criteria**
- Pixel perfect implementaiton
- Responsive implementation
- Clean code
- Make use of reusable components where needed, make one if needed
- Follow the [contribution guidelines](https://github.com/hngprojects/hng_boilerplate_nextjs/blob/0acf613964ea064ae211a91d0a74d13938e4bc23/CONTRIBUTING.md) and [code of conduct](https://github.com/hngprojects/hng_boilerplate_nextjs/blob/0acf613964ea064ae211a91d0a74d13938e4bc23/CODE_OF_CONDUCT.md)

# **Requirements**
- Make a reusable component that accpets props
- Heading prop is required
- Description prop is required

# **Testing**
- Manually test before making a pr

# **Tasks**
- [ ] Implement all the sections in the design
- [ ] Responsiveness across all screens
- [ ] Make use of reusable components where needed
- [ ] Proper commit message

# **Images**
![Hero](https://github.com/user-attachments/assets/389a1612-cf23-492c-b409-989cbcab9890)

[Figma design](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=2349-12237&m=dev)
