### ISSUE TITLE
[FEAT] External static Page > Cookie consent settings (Modal)

### ISSUE THREAD

**Issue by taiwonaf** [hngprojects/hng_boilerplate_remix#33]
# **Description**
Implement both the mobile and web view of the cookie consent settings modal . Implement every content in the page excluding the header and the footer, use already made header and footer if there is a need to. Make use of custom Hero section if need be.

# **Acceptance Criteria**
- Pixel perfect implementaiton
- Responsive implementation
- Clean code
- Make use of reusable components where needed, make one if needed
- Follow the [contribution guidelines](https://github.com/hngprojects/hng_boilerplate_nextjs/blob/0acf613964ea064ae211a91d0a74d13938e4bc23/CONTRIBUTING.md) and [code of conduct](https://github.com/hngprojects/hng_boilerplate_nextjs/blob/0acf613964ea064ae211a91d0a74d13938e4bc23/CODE_OF_CONDUCT.md)

# **Requirements**
- Modal content
- Buttons able to toggle on and off

# **Testing**
- Manually test before making a pr

# **Tasks**
- [x] Implement all the sections in the design
- [x] Responsiveness across all screens
- [x] Make use of reusable components where needed
- [x] Proper commit message

# **Images**

![Cookie consent settings](https://github.com/user-attachments/assets/31c94d89-ff0c-48d1-bb6b-2f1f1bda7f8c)

[Figma design](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=4-23857&m=dev)

**Comment by Kwasako** [comment]
I noticed that the Figma design is completely different from the image. The Figma design is complicated and therefore not user-friendly. Let us implement the design as in the picture.

**Comment by taiwonaf** [comment]
> I noticed that the Figma design is completely different from the image. The Figma design is complicated and therefore not user-friendly. Let us implement the design as in the picture.

follow the figma design, I will update the image attached
