### ISSUE TITLE
[FEAT] Comment Page/Reply page

### ISSUE THREAD

**Issue by Uyimolo** [hngprojects/hng_boilerplate_remix#46]
### Description:
_This ticket outlines the development of nested comment functionality for the comment page. This will allow users to create threaded conversations by replying directly to existing comments, potentially creating nested replies for deeper discussions._

### Acceptance criteria

- Must be responsive across different screen sizes
- Contain a Page Heading ('Comments')
- Contain or capable of containing Comment boxes and nested replies
- Requirements
- Must show all comments concerning a certain product
- Must show or be capable of showing nested replies for comments
- Should show or be capable of showing a text box to reply to comments
- Visually distinguish between parent comments and nested replies: Employ indentation (as seen in the figma design)

### Additional Considerations

- Implement a mechanism to limit the depth of nesting (optional) to prevent excessively complex conversation structures.
- Explore thread collapsing functionality (optional) to allow users to hide nested replies and focus on the main conversation thread.
- Ensure proper loading and rendering of comments and replies, especially for long conversations.
- Maintain efficient performance to avoid lag or slow loading times when dealing with numerous comments and replies.

### Technical Considerations

- Explore efficient data structures and algorithms for managing nested comments to ensure scalability and performance, especially if your application anticipates a high volume of user comments.

###  Labels

- comment, reply, conversation, user-interaction

### Tasks

- [ ]  Get product id param from url (or any other way it is provided)
- [ ]  Fetch comments concerning the product
- [ ]  Iterate through the comments and Display them as seen on the figma file
- [ ]  Ensure replies are hidden on first render (show only the top level comments)
- [ ]  Ensure to create a mechanism for accessing and viewing replies to a comment

### Visual Reference
![image](https://github.com/user-attachments/assets/df0280c2-70cc-4abd-8bbe-8066c80be1f9)
![image](https://github.com/user-attachments/assets/756f6d76-815f-4ad6-9490-79b2c94e22f0)
![image](https://github.com/user-attachments/assets/dfbc44c0-92d1-452d-bd6a-59599da75aff)
![image](https://github.com/user-attachments/assets/d828cdf0-a587-4dcb-bbc0-41cb44fdc097)

**Comment by chrisbanya** [comment]
Get product id param from url (or any other way it is provided)? where is the url?

**Comment by Uyimolo** [comment]
> Get product id param from url (or any other way it is provided)? where is the url?

Use dummy data.

**Comment by chrisbanya** [comment]
link to the figma file?

**Comment by chrisbanya** [comment]
if you are viewing this now. Chrisbanya has assigned this issue to chrisbanya and not planning to unassigned/re-assigned. Goodluck on the next one
